version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5050:5050"
    restart: always
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dashboard
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: always
